package com.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 * wsimport -keep http://localhost:8080/ws/hello?wsdl
 * 
 */
@WebService(name = "Service", targetNamespace = "http://ws.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ClientService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.com/Service/getHelloWorldAsStringRequest", output = "http://ws.com/Service/getHelloWorldAsStringResponse")
    public String getHelloWorldAsString();

}
